CREATE TABLE CLIENTES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (150)
);

CREATE TABLE PEDIDOS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_NOME_ID INTEGER REFERENCES CLIENTES (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC (20,2)
);

CREATE TABLE ITEM_PEDIDOS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ITEM_PRODUTO_ID INTEGER REFERENCES PEDIDOS (ID)
);

CREATE TABLE PRODUTOS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRODUTOS VARCHAR(150),
    QUANTIDADE NUMERIC(20,2)
)